### ISSUE TITLE
Event Loop Error

### ISSUE THREAD

**Issue by webclinic017** [prouhard/pyhoo#4]
~/anaconda3/lib/python3.8/site-packages/pyhoo/__init__.py in get(endpoint, tickers, max_concurrent_calls, ignore_errors, **params)
     22     endpoint_config = endpoints_config[endpoint]
     23     endpoint_config.validate(params)
---> 24     responses = asyncio.run(
     25         Requester(
     26             path=endpoint_config.path,

~/anaconda3/lib/python3.8/asyncio/runners.py in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by prouhard** [comment]
https://github.com/prouhard/pyhoo#troubleshooting
